DROP TABLE IF EXISTS user_details;
CREATE TABLE user_details (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    firstName VARCHAR(50) NOT NULL UNIQUE,
    lastName VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    pwd VARCHAR(255) NOT NULL
);

CREATE TABLE addr_details (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    usr_id INT,
    addr_line1 VARCHAR(100) NOT NULL,
    addr_line2 VARCHAR(100) NOT NULL,
    zipCode VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    FOREIGN KEY (usr_id) REFERENCES user_details(id)
);